spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 2000
            response-timeout: 5s

logging:
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:debug}
    org.springframework.cloud.gateway: ${SPRING_CLOUD_GATEWAY_LOG_LEVEL:info}
